### ISSUE TITLE
Automated Builds

### ISSUE THREAD

**Issue by felicianotech** [cibuilds/snapcraft#1]
Need to decide on a way to automatically build new images and pick up new upstream Docker images.

**Comment by bcardiff** [comment]
+1 

The `cibuilds/snapcraft:stable` has snapcraft 2.43.1
While its upstream `snapcore/snapcraft:stable` has snapcraft 3.5.1

I'm trying to build snaps in CircleCI and I am a bit blocked because circle's image produce outdated snaps and the snapcore's image is unable to pull things from a workspace.

Could the image be updated?

**Comment by felicianotech** [comment]
Yes sir.

I will get this updated today.

**Comment by felicianotech** [comment]
@bcardiff A new image is being pushed to Docker Hub now. It should be available soon.

Keep in mind, the PR linked above will get Snapcraft updated in the image. The Snapcraft Team has done a lot of work in the past year, particularly around bases. I haven't personally tested bases yet in Docker/CircleCI so I don't know how well it will work yet.

**Comment by bcardiff** [comment]
Thanks @felicianotech! The new circle image is able to produce a working snap
